name = "TwoQubitWeylChamber"
uuid = "cad078a0-0012-46f4-b55e-a945d44e115b"
authors = ["Michael Goerz <mail@michaelgoerz.net>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
julia = "1.6"
